"""Westminster parliamentary constituencies in England (2024 boundaries).

The 543 names as published in Tax Policy Associates' constituency council-tax
band file (sources/harvest-uk-ab2025-2026-09-24/uk_tpa, constituency_council_tax_bands.geojson),
vendored so a constituency-grain geography is a closed identity rather than
prose. Spelling follows the file; a source that spells a constituency
differently registers an alias in uk_aliases.py, never a second identity.
"""

ENGLAND_WESTMINSTER_CONSTITUENCIES_2024: tuple[str, ...] = (
    "Aldershot",
    "Aldridge-Brownhills",
    "Altrincham and Sale West",
    "Amber Valley",
    "Arundel and South Downs",
    "Ashfield",
    "Ashford",
    "Ashton-under-Lyne",
    "Aylesbury",
    "Banbury",
    "Barking",
    "Barnsley North",
    "Barnsley South",
    "Barrow and Furness",
    "Basildon and Billericay",
    "Basingstoke",
    "Bassetlaw",
    "Bath",
    "Battersea",
    "Beaconsfield",
    "Beckenham and Penge",
    "Bedford",
    "Bermondsey and Old Southwark",
    "Bethnal Green and Stepney",
    "Beverley and Holderness",
    "Bexhill and Battle",
    "Bexleyheath and Crayford",
    "Bicester and Woodstock",
    "Birkenhead",
    "Birmingham Edgbaston",
    "Birmingham Erdington",
    "Birmingham Hall Green and Moseley",
    "Birmingham Hodge Hill and Solihull North",
    "Birmingham Ladywood",
    "Birmingham Northfield",
    "Birmingham Perry Barr",
    "Birmingham Selly Oak",
    "Birmingham Yardley",
    "Bishop Auckland",
    "Blackburn",
    "Blackley and Middleton South",
    "Blackpool North and Fleetwood",
    "Blackpool South",
    "Blaydon and Consett",
    "Blyth and Ashington",
    "Bognor Regis and Littlehampton",
    "Bolsover",
    "Bolton North East",
    "Bolton South and Walkden",
    "Bolton West",
    "Bootle",
    "Boston and Skegness",
    "Bournemouth East",
    "Bournemouth West",
    "Bracknell",
    "Bradford East",
    "Bradford South",
    "Bradford West",
    "Braintree",
    "Brent East",
    "Brent West",
    "Brentford and Isleworth",
    "Brentwood and Ongar",
    "Bridgwater",
    "Bridlington and The Wolds",
    "Brigg and Immingham",
    "Brighton Kemptown and Peacehaven",
    "Brighton Pavilion",
    "Bristol Central",
    "Bristol East",
    "Bristol North East",
    "Bristol North West",
    "Bristol South",
    "Broadland and Fakenham",
    "Bromley and Biggin Hill",
    "Bromsgrove",
    "Broxbourne",
    "Broxtowe",
    "Buckingham and Bletchley",
    "Burnley",
    "Burton and Uttoxeter",
    "Bury North",
    "Bury South",
    "Bury St Edmunds and Stowmarket",
    "Calder Valley",
    "Camborne and Redruth",
    "Cambridge",
    "Cannock Chase",
    "Canterbury",
    "Carlisle",
    "Carshalton and Wallington",
    "Castle Point",
    "Central Devon",
    "Central Suffolk and North Ipswich",
    "Chatham and Aylesford",
    "Cheadle",
    "Chelmsford",
    "Chelsea and Fulham",
    "Cheltenham",
    "Chesham and Amersham",
    "Chester North and Neston",
    "Chester South and Eddisbury",
    "Chesterfield",
    "Chichester",
    "Chingford and Woodford Green",
    "Chippenham",
    "Chipping Barnet",
    "Chorley",
    "Christchurch",
    "Cities of London and Westminster",
    "City of Durham",
    "Clacton",
    "Clapham and Brixton Hill",
    "Colchester",
    "Colne Valley",
    "Congleton",
    "Corby and East Northamptonshire",
    "Coventry East",
    "Coventry North West",
    "Coventry South",
    "Cramlington and Killingworth",
    "Crawley",
    "Crewe and Nantwich",
    "Croydon East",
    "Croydon South",
    "Croydon West",
    "Dagenham and Rainham",
    "Darlington",
    "Dartford",
    "Daventry",
    "Derby North",
    "Derby South",
    "Derbyshire Dales",
    "Dewsbury and Batley",
    "Didcot and Wantage",
    "Doncaster Central",
    "Doncaster East and the Isle of Axholme",
    "Doncaster North",
    "Dorking and Horley",
    "Dover and Deal",
    "Droitwich and Evesham",
    "Dudley",
    "Dulwich and West Norwood",
    "Dunstable and Leighton Buzzard",
    "Ealing Central and Acton",
    "Ealing North",
    "Ealing Southall",
    "Earley and Woodley",
    "Easington",
    "East Grinstead and Uckfield",
    "East Ham",
    "East Hampshire",
    "East Surrey",
    "East Thanet",
    "East Wiltshire",
    "East Worthing and Shoreham",
    "Eastbourne",
    "Eastleigh",
    "Edmonton and Winchmore Hill",
    "Ellesmere Port and Bromborough",
    "Eltham and Chislehurst",
    "Ely and East Cambridgeshire",
    "Enfield North",
    "Epping Forest",
    "Epsom and Ewell",
    "Erewash",
    "Erith and Thamesmead",
    "Esher and Walton",
    "Exeter",
    "Exmouth and Exeter East",
    "Fareham and Waterlooville",
    "Farnham and Bordon",
    "Faversham and Mid Kent",
    "Feltham and Heston",
    "Filton and Bradley Stoke",
    "Finchley and Golders Green",
    "Folkestone and Hythe",
    "Forest of Dean",
    "Frome and East Somerset",
    "Fylde",
    "Gainsborough",
    "Gateshead Central and Whickham",
    "Gedling",
    "Gillingham and Rainham",
    "Glastonbury and Somerton",
    "Gloucester",
    "Godalming and Ash",
    "Goole and Pocklington",
    "Gorton and Denton",
    "Gosport",
    "Grantham and Bourne",
    "Gravesham",
    "Great Grimsby and Cleethorpes",
    "Great Yarmouth",
    "Greenwich and Woolwich",
    "Guildford",
    "Hackney North and Stoke Newington",
    "Hackney South and Shoreditch",
    "Halesowen",
    "Halifax",
    "Hamble Valley",
    "Hammersmith and Chiswick",
    "Hampstead and Highgate",
    "Harborough, Oadby and Wigston",
    "Harlow",
    "Harpenden and Berkhamsted",
    "Harrogate and Knaresborough",
    "Harrow East",
    "Harrow West",
    "Hartlepool",
    "Harwich and North Essex",
    "Hastings and Rye",
    "Havant",
    "Hayes and Harlington",
    "Hazel Grove",
    "Hemel Hempstead",
    "Hendon",
    "Henley and Thame",
    "Hereford and South Herefordshire",
    "Herne Bay and Sandwich",
    "Hertford and Stortford",
    "Hertsmere",
    "Hexham",
    "Heywood and Middleton North",
    "High Peak",
    "Hinckley and Bosworth",
    "Hitchin",
    "Holborn and St Pancras",
    "Honiton and Sidmouth",
    "Hornchurch and Upminster",
    "Hornsey and Friern Barnet",
    "Horsham",
    "Houghton and Sunderland South",
    "Hove and Portslade",
    "Huddersfield",
    "Huntingdon",
    "Hyndburn",
    "Ilford North",
    "Ilford South",
    "Ipswich",
    "Isle of Wight East",
    "Isle of Wight West",
    "Islington North",
    "Islington South and Finsbury",
    "Jarrow and Gateshead East",
    "Keighley and Ilkley",
    "Kenilworth and Southam",
    "Kensington and Bayswater",
    "Kettering",
    "Kingston and Surbiton",
    "Kingston upon Hull East",
    "Kingston upon Hull North and Cottingham",
    "Kingston upon Hull West and Haltemprice",
    "Kingswinford and South Staffordshire",
    "Knowsley",
    "Lancaster and Wyre",
    "Leeds Central and Headingley",
    "Leeds East",
    "Leeds North East",
    "Leeds North West",
    "Leeds South",
    "Leeds South West and Morley",
    "Leeds West and Pudsey",
    "Leicester East",
    "Leicester South",
    "Leicester West",
    "Leigh and Atherton",
    "Lewes",
    "Lewisham East",
    "Lewisham North",
    "Lewisham West and East Dulwich",
    "Leyton and Wanstead",
    "Lichfield",
    "Lincoln",
    "Liverpool Garston",
    "Liverpool Riverside",
    "Liverpool Walton",
    "Liverpool Wavertree",
    "Liverpool West Derby",
    "Loughborough",
    "Louth and Horncastle",
    "Lowestoft",
    "Luton North",
    "Luton South and South Bedfordshire",
    "Macclesfield",
    "Maidenhead",
    "Maidstone and Malling",
    "Makerfield",
    "Maldon",
    "Manchester Central",
    "Manchester Rusholme",
    "Manchester Withington",
    "Mansfield",
    "Melksham and Devizes",
    "Melton and Syston",
    "Meriden and Solihull East",
    "Mid Bedfordshire",
    "Mid Buckinghamshire",
    "Mid Cheshire",
    "Mid Derbyshire",
    "Mid Dorset and North Poole",
    "Mid Leicestershire",
    "Mid Norfolk",
    "Mid Sussex",
    "Middlesbrough South and East Cleveland",
    "Middlesbrough and Thornaby East",
    "Milton Keynes Central",
    "Milton Keynes North",
    "Mitcham and Morden",
    "Morecambe and Lunesdale",
    "New Forest East",
    "New Forest West",
    "Newark",
    "Newbury",
    "Newcastle upon Tyne Central and West",
    "Newcastle upon Tyne East and Wallsend",
    "Newcastle upon Tyne North",
    "Newcastle-under-Lyme",
    "Newton Abbot",
    "Newton Aycliffe and Spennymoor",
    "Normanton and Hemsworth",
    "North Bedfordshire",
    "North Cornwall",
    "North Cotswolds",
    "North Devon",
    "North Dorset",
    "North Durham",
    "North East Cambridgeshire",
    "North East Derbyshire",
    "North East Hampshire",
    "North East Hertfordshire",
    "North East Somerset and Hanham",
    "North Herefordshire",
    "North Norfolk",
    "North Northumberland",
    "North Shropshire",
    "North Somerset",
    "North Warwickshire and Bedworth",
    "North West Cambridgeshire",
    "North West Essex",
    "North West Hampshire",
    "North West Leicestershire",
    "North West Norfolk",
    "Northampton North",
    "Northampton South",
    "Norwich North",
    "Norwich South",
    "Nottingham East",
    "Nottingham North and Kimberley",
    "Nottingham South",
    "Nuneaton",
    "Old Bexley and Sidcup",
    "Oldham East and Saddleworth",
    "Oldham West, Chadderton and Royton",
    "Orpington",
    "Ossett and Denby Dale",
    "Oxford East",
    "Oxford West and Abingdon",
    "Peckham",
    "Pendle and Clitheroe",
    "Penistone and Stocksbridge",
    "Penrith and Solway",
    "Peterborough",
    "Plymouth Moor View",
    "Plymouth Sutton and Devonport",
    "Pontefract, Castleford and Knottingley",
    "Poole",
    "Poplar and Limehouse",
    "Portsmouth North",
    "Portsmouth South",
    "Preston",
    "Putney",
    "Queen's Park and Maida Vale",
    "Rawmarsh and Conisbrough",
    "Rayleigh and Wickford",
    "Reading Central",
    "Reading West and Mid Berkshire",
    "Redcar",
    "Redditch",
    "Reigate",
    "Ribble Valley",
    "Richmond Park",
    "Richmond and Northallerton",
    "Rochdale",
    "Rochester and Strood",
    "Romford",
    "Romsey and Southampton North",
    "Rossendale and Darwen",
    "Rother Valley",
    "Rotherham",
    "Rugby",
    "Ruislip, Northwood and Pinner",
    "Runcorn and Helsby",
    "Runnymede and Weybridge",
    "Rushcliffe",
    "Rutland and Stamford",
    "Salford",
    "Salisbury",
    "Scarborough and Whitby",
    "Scunthorpe",
    "Sefton Central",
    "Selby",
    "Sevenoaks",
    "Sheffield Brightside and Hillsborough",
    "Sheffield Central",
    "Sheffield Hallam",
    "Sheffield Heeley",
    "Sheffield South East",
    "Sherwood Forest",
    "Shipley",
    "Shrewsbury",
    "Sittingbourne and Sheppey",
    "Skipton and Ripon",
    "Sleaford and North Hykeham",
    "Slough",
    "Smethwick",
    "Solihull West and Shirley",
    "South Basildon and East Thurrock",
    "South Cambridgeshire",
    "South Cotswolds",
    "South Derbyshire",
    "South Devon",
    "South Dorset",
    "South East Cornwall",
    "South Holland and The Deepings",
    "South Leicestershire",
    "South Norfolk",
    "South Northamptonshire",
    "South Ribble",
    "South Shields",
    "South Shropshire",
    "South Suffolk",
    "South West Devon",
    "South West Hertfordshire",
    "South West Norfolk",
    "South West Wiltshire",
    "Southampton Itchen",
    "Southampton Test",
    "Southend East and Rochford",
    "Southend West and Leigh",
    "Southgate and Wood Green",
    "Southport",
    "Spelthorne",
    "Spen Valley",
    "St Albans",
    "St Austell and Newquay",
    "St Helens North",
    "St Helens South and Whiston",
    "St Ives",
    "St Neots and Mid Cambridgeshire",
    "Stafford",
    "Staffordshire Moorlands",
    "Stalybridge and Hyde",
    "Stevenage",
    "Stockport",
    "Stockton North",
    "Stockton West",
    "Stoke-on-Trent Central",
    "Stoke-on-Trent North",
    "Stoke-on-Trent South",
    "Stone, Great Wyrley and Penkridge",
    "Stourbridge",
    "Stratford and Bow",
    "Stratford-on-Avon",
    "Streatham and Croydon North",
    "Stretford and Urmston",
    "Stroud",
    "Suffolk Coastal",
    "Sunderland Central",
    "Surrey Heath",
    "Sussex Weald",
    "Sutton Coldfield",
    "Sutton and Cheam",
    "Swindon North",
    "Swindon South",
    "Tamworth",
    "Tatton",
    "Taunton and Wellington",
    "Telford",
    "Tewkesbury",
    "The Wrekin",
    "Thirsk and Malton",
    "Thornbury and Yate",
    "Thurrock",
    "Tipton and Wednesbury",
    "Tiverton and Minehead",
    "Tonbridge",
    "Tooting",
    "Torbay",
    "Torridge and Tavistock",
    "Tottenham",
    "Truro and Falmouth",
    "Tunbridge Wells",
    "Twickenham",
    "Tynemouth",
    "Uxbridge and South Ruislip",
    "Vauxhall and Camberwell Green",
    "Wakefield and Rothwell",
    "Wallasey",
    "Walsall and Bloxwich",
    "Walthamstow",
    "Warrington North",
    "Warrington South",
    "Warwick and Leamington",
    "Washington and Gateshead South",
    "Watford",
    "Waveney Valley",
    "Weald of Kent",
    "Wellingborough and Rushden",
    "Wells and Mendip Hills",
    "Welwyn Hatfield",
    "West Bromwich",
    "West Dorset",
    "West Ham and Beckton",
    "West Lancashire",
    "West Suffolk",
    "West Worcestershire",
    "Westmorland and Lonsdale",
    "Weston-super-Mare",
    "Wetherby and Easingwold",
    "Whitehaven and Workington",
    "Widnes and Halewood",
    "Wigan",
    "Wimbledon",
    "Winchester",
    "Windsor",
    "Wirral West",
    "Witham",
    "Witney",
    "Woking",
    "Wokingham",
    "Wolverhampton North East",
    "Wolverhampton South East",
    "Wolverhampton West",
    "Worcester",
    "Worsley and Eccles",
    "Worthing West",
    "Wycombe",
    "Wyre Forest",
    "Wythenshawe and Sale East",
    "Yeovil",
    "York Central",
    "York Outer",
)
