"""Derive the OBR costings claims slice from the vendored harvest (#56).

`sources/harvest-20260802/uk_obr/obr_costings_claims.jsonl` is the 621-row
slice of the OBR Policy Measures Database (November 2025 vintage) and the
EFO March 2026 Table 3.17 re-estimates that `data/uk/obr_measure_reforms.yaml`
scores. It was cut by hand from a harvest file outside the repository, so
nothing could re-derive it (gate round 1, finding 3). This script derives
it from the harvest the repository vendors,
`sources/harvest-uk-2026-08-02/uk_obr/claims_staged.jsonl.gz` (25,558 rows,
sha256 in that family's manifest), with an exact selected / not-selected
tally, and `--check` fails if the committed slice differs by a byte.

Selection rule (the registry is the only input besides the harvest):
  * source == "obr";
  * reform_hint == a registry measure's verbatim obr_description;
  * Policy Measures Database rows (either the Tax or the Spending table)
    must carry the measure's fiscal_event; a measure's spending heads
    live in the Spending table even when the registry names the Tax
    table, so the table is not a filter for PMD rows;
  * EFO Table 3.17 rows match only measures whose registry source_table
    is "3.17: 3.17" (the March 2026 re-estimates carry no fiscal_event).
Rows are written in harvest order, one JSON object per line.

It also writes `obr_costings_measures.json`, the JSON projection of the
YAML registry the DB ingest reads (the build chain has no YAML
dependency; tests, which run with PyYAML, check the projection against
the YAML byte for byte).

    PYTHONPATH=. uv run --with pyyaml python pipeline/select_obr_costings_claims.py
    PYTHONPATH=. uv run --with pyyaml python pipeline/select_obr_costings_claims.py --check
"""

from __future__ import annotations

import gzip
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "data" / "uk" / "obr_measure_reforms.yaml"
HARVEST = (
    ROOT / "sources" / "harvest-uk-2026-08-02" / "uk_obr" / "claims_staged.jsonl.gz"
)
OUT_DIR = ROOT / "sources" / "harvest-20260802" / "uk_obr"
SLICE = OUT_DIR / "obr_costings_claims.jsonl"
INDEX = OUT_DIR / "obr_costings_measures.json"

PMD_TABLES = frozenset(
    {
        "Tax Measures (Policy measures database)",
        "Spending Measures (Policy measures database)",
    }
)
EFO_317 = "3.17: 3.17"

# The registry fields the DB ingest and the staging resolver consume.
INDEX_FIELDS = (
    "measure_key",
    "fiscal_event",
    "obr_description",
    "source_table",
    "external_metric",
    "start_fy",
    "computability",
    "construction",
    "notes",
)


def load_registry() -> dict:
    import yaml  # tests and this script run with PyYAML; the build does not

    return yaml.safe_load(REGISTRY.read_text())


def measure_index(reg: dict) -> dict:
    measures = []
    for m in reg["measures"]:
        entry = {k: m.get(k) for k in INDEX_FIELDS}
        entry["has_pe_reform"] = bool(m.get("pe_reform"))
        entry["heads"] = [
            {
                "obr_head": h["obr_head"],
                "condition_key": h.get("condition_key"),
                "source_table": h.get("source_table", m["source_table"]),
                "channel": h.get("channel"),
            }
            for h in m.get("heads", [])
        ]
        entry["unmapped_obr_heads"] = list(m.get("unmapped_obr_heads") or [])
        measures.append(entry)
    return {
        "derived_from": str(REGISTRY.relative_to(ROOT)),
        "rule": (
            "JSON projection of the YAML registry for the DB ingest and the "
            "staging resolver; regenerated by pipeline/select_obr_costings_claims.py "
            "and checked against the YAML by tests"
        ),
        "measures": measures,
    }


def select(reg: dict) -> tuple[list[dict], dict]:
    measures = reg["measures"]
    by_desc: dict[str, list[dict]] = {}
    for m in measures:
        by_desc.setdefault(m["obr_description"], []).append(m)
    selected: list[dict] = []
    tally = {
        "read": 0,
        "selected": 0,
        "not_selected": {
            "other_source": 0,
            "description_not_in_registry": 0,
            "other_fiscal_event": 0,
            "other_table": 0,
        },
    }
    with gzip.open(HARVEST, "rt") as fh:
        for line in fh:
            row = json.loads(line)
            tally["read"] += 1
            if row.get("source") != "obr":
                tally["not_selected"]["other_source"] += 1
                continue
            candidates = by_desc.get(row.get("reform_hint"))
            if not candidates:
                tally["not_selected"]["description_not_in_registry"] += 1
                continue
            table = row.get("source_table")
            event = (row.get("conditions") or {}).get("fiscal_event")
            hit = None
            for m in candidates:
                if table == EFO_317:
                    if m["source_table"] == EFO_317:
                        hit = m
                        break
                elif table in PMD_TABLES and event == m["fiscal_event"]:
                    hit = m
                    break
            if hit is None:
                if table not in PMD_TABLES and table != EFO_317:
                    tally["not_selected"]["other_table"] += 1
                else:
                    tally["not_selected"]["other_fiscal_event"] += 1
                continue
            selected.append(row)
            tally["selected"] += 1
    return selected, tally


def render(rows: list[dict]) -> str:
    return "".join(json.dumps(r) + "\n" for r in rows)


def render_index(index: dict) -> str:
    return json.dumps(index, indent=1, ensure_ascii=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    reg = load_registry()
    rows, tally = select(reg)
    slice_text = render(rows)
    index_text = render_index(measure_index(reg))
    if "--check" in argv:
        if not SLICE.exists() or SLICE.read_text() != slice_text:
            raise SystemExit(f"{SLICE} differs from the derived slice ({tally})")
        if not INDEX.exists() or INDEX.read_text() != index_text:
            raise SystemExit(f"{INDEX} differs from the YAML projection")
        print(f"slice reproduces byte for byte: {tally}")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    SLICE.write_text(slice_text)
    INDEX.write_text(index_text)
    print(json.dumps(tally))
    return 0


if __name__ == "__main__":
    sys.exit(main())
