const SOURCE_SPECIAL: Record<string, string> = {
  jct: "JCT",
  cbo: "CBO",
  irs: "IRS",
  irs_soi: "IRS SOI",
  census: "Census",
  census_pep: "Census PEP",
  treasury: "Treasury",
  tpc: "TPC",
  pwbm: "PWBM",
  cpsp: "Columbia CPSP",
  budget_lab: "Budget Lab",
  tax_foundation: "Tax Foundation",
  obr: "OBR",
  hmrc: "HMRC",
  uk_hmrc: "HMRC",
  dwp: "DWP",
  dwp_takeup: "DWP take-up",
  dwp_hbai: "DWP HBAI",
  hmt: "HMT",
  hm_treasury: "HM Treasury",
  ifs: "IFS",
  rf: "Resolution Foundation",
  resolution_foundation: "Resolution Foundation",
  ukmod: "UKMOD",
  jrc_euromod: "JRC EUROMOD",
  spf_finances: "SPF Finances",
  cour_des_comptes: "Cour des comptes",
  nz_treasury: "New Zealand Treasury",
  policyengine: "PolicyEngine",
  obr_policy_effects: "OBR policy effects",
  // Autumn Budget 2025 port (#136): every producer that scored the Budget
  obr_efo: "OBR (EFO tables)",
  jrf: "JRF",
  ippr: "IPPR",
  cpag: "CPAG",
  fraser_of_allander: "Fraser of Allander Institute",
  scottish_fiscal_commission: "Scottish Fiscal Commission",
  wbg: "Women's Budget Group",
  centax: "CenTax",
  tax_policy_associates: "Tax Policy Associates",
  policy_in_practice: "Policy in Practice",
  entitledto: "entitledto",
  nef: "New Economics Foundation",
  cebr: "Cebr",
  smf: "Social Market Foundation",
  public_first: "Public First",
  demos: "Demos",
  fabian_society: "Fabian Society",
  taxpayers_alliance: "TaxPayers' Alliance",
  cps: "Centre for Policy Studies",
  onward: "Onward",
  tax_justice_uk: "Tax Justice UK",
  iea: "Institute of Economic Affairs",
  policy_exchange: "Policy Exchange",
  ppi: "Pensions Policy Institute",
  loughborough_crsp: "Loughborough CRSP",
  trussell_wpi: "Trussell / WPI Economics",
  niesr: "NIESR",
};

export function sourceLabel(s: string): string {
  if (SOURCE_SPECIAL[s]) return SOURCE_SPECIAL[s];
  const m = s.match(/^([a-z]{2})_(admin|fiscal_note)$/);
  if (m) return `${m[1].toUpperCase()} ${m[2].replace("_", " ")}`;
  return s;
}
